stages:
  - check
  - build
  - publish

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 3
  GIT_CLEAN_FLAGS: -f
  CACHE_IMAGE_TAG: e0ef5539
  TAG_REGEX: '/^v[0-9]+\.[0-9]+\.[0-9]+$/'

default:
  interruptible: true
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  tags:
    - veloren/veloren

  # NOTE: The `.build-macos-x86_64` and `.build-macos-aarch64` job templates
  # override this keyword so relevant changes need to be mirrored there.
  before_script:
    - source ${HOME}/.cargo/env;
    - df -h /;
    - free -h;
    - cargo --version;
    - source ./.gitlab/scripts/env.sh;
    - rm -rf target || echo "it seems that sometimes OLD data is left over";

# 8866215 is the user that is used to sync data to the collaboration repos.
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $GITLAB_USER_ID != "8866215"
    - if: $CI_COMMIT_REF_NAME =~ /^r[0-9]+\.[0-9]+/ && $GITLAB_USER_ID != "8866215"

include:
  - local: .gitlab/CI/templates.yml
  - local: .gitlab/CI/check.gitlab-ci.yml
  - local: .gitlab/CI/build.gitlab-ci.yml
  - local: .gitlab/CI/publish.gitlab-ci.yml
