code-quality:
  extends: .run-on-code-changes
  stage: check
  image: registry.gitlab.com/veloren/veloren-docker-ci/cache/quality:${CACHE_IMAGE_TAG}
  tags: ["veloren/veloren", "check"]
  variables:
    # Disables shallow cloning - full history of the source branch is needed
    # for the 'git lfs fsck' command below.
    GIT_DEPTH: 0
  script:
    - echo ${CI_COMMIT_TAG};
    - echo ${TAG_REGEX};
    - ln -s /dockercache/target target;
    - cat ./.gitlab/scripts/code-quality.sh;
    - source ./.gitlab/scripts/code-quality.sh;
    # Brings the target branch into the job's scope - used to define
    # the full range of commits between the target and merged result.
    - git fetch origin ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}:refs/remotes/origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME};
    - git lfs fsck --pointers origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}..HEAD;

security:
  extends: .run-on-code-changes
  stage: check
  image: registry.gitlab.com/veloren/veloren-docker-ci/cache/quality:${CACHE_IMAGE_TAG}
  tags: ["veloren/veloren", "check"]
  allow_failure: true
  script:
    - ln -s /dockercache/target target;
    - cat ./.gitlab/scripts/security.sh;
    - source ./.gitlab/scripts/security.sh;
